version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.3
    - 2.42.4
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: element-ui
    versions:
    - 2.15.0
